import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import Navbar from "./components/Navbar";
import { AddMemberModalProvider } from "./contexts/addMemberModalContext";
import { MembersProvider } from "./contexts/MembersContext";
import { RolesProvider } from "./contexts/RolesContext";
import { MessagesProvider } from "./contexts/MessagesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MembersProvider>
        <RolesProvider>
          <MessagesProvider>
            <AddMemberModalProvider>
              <div className="flex h-screen w-full overflow-hidden">
                <Sidebar />

                <div className="flex flex-col flex-1 overflow-hidden">
                  <Navbar />

                  <main className="bg-[#1a1a1e] flex-1 overflow-y-auto bg-muted p-4">
                    {children}
                  </main>
                </div>
              </div>
            </AddMemberModalProvider>
          </MessagesProvider>
        </RolesProvider>
        </MembersProvider>
      </body>
    </html>
  );
}
